version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
    groups:
      minor-and-patch:
        applies-to: version-updates
        exclude-patterns:
          - "@angular*"
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
    directories:
      - "/client"
      - "/CDK"
    groups:
      typescript:
        applies-to: version-updates
        patterns:
          - "typescript"
        update-types:
          - "patch"
          - "minor"
      angular:
        applies-to: version-updates
        patterns:
          - "@angular*"
        update-types:
          - "minor"
          - "patch"
      minor-and-patch:
        applies-to: version-updates
        exclude-patterns:
          - "@angular*"
        update-types:
          - "patch"
          - "minor"