version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
    directories:
      - "/client"
      - "/CDK"