version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/food-orde/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  key-clock:
    container_name: "key-clock"
    image: "quay.io/keycloak/keycloak:24.0.2"
    ports:
      - "8180:8080"
    volumes:
      - "./import:/opt/keycloak/data/import"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command:
     - "start-dev"
     - "--import-realm"

