version: '3.8'
services:
  localstack:
    image: "localstack/localstack"
    hostname: "localstack"
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - PERSISTENCE=1
    volumes:
      - "./local_stack:/etc/localstack/init/ready.d"
      - "./dynamodb_volume:/var/lib/localstack"
  food-order-server:
    container_name: "food-order-server"
    image: "sharedfoodorder:latest"
    ports:
      - "8080:8080"
    environment:
      OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
      OAUTH_CLIENT_SECRET: "${OAUTH_CLIENT_SECRET}"
      OAUTH_DOMAIN: "${OAUTH_DOMAIN}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-123}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY:-123}"
      DYNAMODB_URL: "http://localstack:4566"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - localstack