version: '3.8'
services:
  localstack:
    image: "localstack/localstack"
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
    volumes:
      - "/Users/stevenmeek/sharedfoodorder/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
  key-clock:
    container_name: "key-clock"
    image: "quay.io/keycloak/keycloak:24.0.2"
    ports:
      - "8180:8080"
    volumes:
      - "./import:/opt/keycloak/data/import"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command:
     - "start-dev"
     - "--import-realm"

