micronaut:
  deserialization:
    readDateTimestampsAsNanoseconds: false
    READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  server:
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - http://localhost:8080
            - http://localhost:4200
  security:
    authentication: cookie
    oauth2:
      pkce:
        enabled: false
      clients:
        auth0:
          client-id: '${OAUTH_CLIENT_ID}'
          client-secret: '${OAUTH_CLIENT_SECRET}'
          openid:
            issuer: 'https://${OAUTH_DOMAIN}/'
  dynamodb:
    primary_table:
      region: "http://localstack:4566"
      endpoint: "eu-west-1"

endpoints:
  routes:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false

jackson:
  deserialization:
    readDateTimestampsAsNanoseconds: false
    READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  serialization:
    WRITE_DATE_TIMESTAMP_AS_NANOSECONDS: false
  serialization-inclusion: always